# 期约与异步函数

## 期约(Promise)

### 1.期约状态：
期约是一个有状态的对象
  - 待定pending
  - 兑现fulfilled或者 解决resolved
  - 拒绝rejected

比如打印一个期约：
```javascript
let p = new Promise((resolve,reject)=>{
  resolve(3)
})
console.log(p) //Promise {<fulfilled>: 3}
```

### 2.实例化期约
  - new Promise()
  - Promise.resolve() 实例化一个解决期约
  - Promise.reject() 实例化一个拒绝期约

### 3.期约的实例方法：then
  -  注意和new Promise做区别，new Promise接收一个执行器函数，then方法接收两个可选参数：onResolved处理程序、onRejected处理程序，如果第一个不传则填null，避免在内存中创建多余对象。
  - then返回一个新期约实例
  - then两个处理程序都不传，则原样向后传
  - then没有明显返回值时，默认返回Promise.resolve包装过的undefined

```javascript
let p = new Promise((resolve,reject)=>{
  resolve(3)
}).then((res)=>{
  console.log(res) //3
}).then((res)=>{
  console.log(res) //undefined,没有明显返回值时，默认返回Promise.resolve包装过的undefined
})
```

### 4.期约的实例方法：catch
相当于调用Promise.prototype.then(null, onRejected)

### 5.期约的实例方法：finally
  -  接收一个onFinally处理程序
  - 期约为拒绝或解决都会调用finally，主要用来添加清理代码
  - 如果finally后面还有连缀或者其他操作：
    - 多数情况原样往后传 父期约 
    - 如果finally自己返回一个待定期约、拒绝期约、抛出错误，则返回相应的期约（待定或拒绝）

### 6.then、catch、finally是微任务
期约落定状态后，其处理程序（then、catch等）会被排期，而不是立即执行。
微任务、宏任务和JS的事件循环机制有关，可参考本人的另一篇文章：[JS执行机制](../JS基础/JS执行机制.md)

### 7.抛出错误或者拒绝期约，没有处理的话，都会抛出未捕获错误
```javascript
let p = Promise.reject("xx")

Uncaught (in promise) xx
```
而且错误是异步抛出的，不会阻止运行时继续执行同步命令。

因此不能用try catch这种同步结构捕获错误，而要通过异步的处理程序捕获(then、catch、finally)

注意这个例子：
```javascript
let p1 = Promise.reject("1")
let p2 = Promise.resolve().then(()=>{throw Error("2:拒绝")})
let p3 = Promise.resolve().then(()=>{console.log("3:解决")})
let p4 = Promise.reject(Error("4"))

//出现顺序
	3:解决
	Uncaught (in promise) 1
	Uncaught (in promise) Error: 4	
	Uncaught (in promise) Error: 2:拒绝
```

🙄可以看到Promise.resolve().then的错误最后才出现，因为它需要在运行时消息队列中添加处理程序

🙄并且，当微任务队列清空后，才会处理错误 

### 8.Promise.all、Promise.race的注意点
  - 它们接收的是可迭代对象，里面的元素会通过Pomise.resolve转换成期约
  - all有一个为拒绝期约，后面的期约还是会被静默处理（即还是有执行）
  - race同理


## 异步函数Async await
异步函数是期约模式在函数中的应用，使得可以以同步的书写方式来写异步代码。

### 1.async关键字
  - async关键字让函数具有异步特征，但是其代码仍然是同步求值的。

  - 如果async函数用使用return返回了值，则返回值会被Promise.resolve包装成一个期约对象；如果没有return，则返回undefined

  - async函数里面的拒绝期约不会被捕获

```javascript
async function foo(){
  Promise.reject("err")
}
foo().catch(console.log)

//Uncaught (in promise) err
```

### 2.await关键字
  - await可以暂停异步函数的执行
  - await后面如果跟一个拒绝期约，那么会被catch捕获（和async相反）
  ```javascript
  async function foo(){
    await Promise.reject("err")
  }
  foo().catch(console.log)
  // err
  ```

  - js遇到await时，会记录在哪里暂停执行，等await右边的值可用了，js运行时会向消息队列推送一个任务，以恢复异步函数的执行
  - 即使await右边是立即可用的值，函数的其余部分也会异步求值
  - 如果await右边是一个期约，为了执行异步函数，实际上会有2个任务被添加到消息队列，并被异步求值。第一个任务是 期约在落定之后执行，期约立即落定，再添加 给await提供值 的任务。

可以比较下面的例子：
```javascript
async function test(){
  return 8
}

async function foo(){
  console.log(2)
  console.log(await test())
  console.log(9)
}
async function bar(){
  console.log(4)
  console.log(await 6)
  console.log(7)
}
console.log(1)
foo()
console.log(3)
bar()
console.log(5)

//打印顺序：1 2 3 4 5 8 9 6 7
```

```javascript
async function foo(){
  console.log(2)
  console.log(await new Promise((resolve,reject)=>{
    console.log('xx')
    resolve(8)
  }))
  console.log(9)
}
async function bar(){
  console.log(4)
  console.log(await 6)
  console.log(7)
}
console.log(1)
foo()
console.log(3)
bar()
console.log(5)

//打印顺序：1 2 xx 3 4 5 8 9 6 7
```

```javascript

async function foo(){
  console.log(2)
  
  console.log(await new Promise((resolve,reject)=>{
    console.log('xx')
    resolve()
  }).then(()=>{
    console.log("yy")
  }).then(()=>{
    console.log("zz")
    return 8
  }))
  
  console.log(9)
}
async function bar(){
  console.log(4)
  console.log(await 6)
  console.log(7)
}
console.log(1)
foo()
console.log(3)
bar()
console.log(5)

// 1 2 xx 3 4 5 yy 6 7 zz 8 9
```

注意：是等到await右边的值可以用了，js运行时会向消息队列推送一个 恢复异步函数执行 的任务。这个任务会在同步代码执行完毕后被提取。